version: 2.1

jobs:
  build-and-test:
    executor: python/default
  =======
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python main.py
workflows:
  build_and_test:
    jobs:
      - build